name: Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: vps.bluelaser.cn
          username: yaka
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/yaka/Nanochat
            git checkout -- .
            git sparse-checkout init
            git sparse-checkout set "server"
            git config pull.rebase false
            git pull origin main
            cd server
            sudo systemctl restart docker
            sudo docker compose build api
            sudo docker compose up -d api
